const bigBasketCategories = [
  {
    category: "groceries",
    subcategory: "fruits",
    url: "https://www.bigbasket.com/ps/?q=fruits",
    selectors: {
      item: "div.SKUDeck___StyledDiv-sc-1e5d9gk-0",
      name: "h3",
      quantity: "span.hZcweF span",
      actualPrice: "span.a-text-price",
      discountedPrice: "span.knDrlZ",
      discountDetail: null,
      image: "img",
      details: null,
      link: "a",
    },
  },
  {
    category: "groceries",
    subcategory: "vegetables",
    url: "https://www.bigbasket.com/ps/?q=vegetables",
    selectors: {
      item: "div.SKUDeck___StyledDiv-sc-1e5d9gk-0",
      name: "h3",
      quantity: "span.hZcweF span",
      actualPrice: "span.a-text-price",
      discountedPrice: "span.knDrlZ",
      discountDetail: null,
      image: "img",
      details: null,
      link: "a",
    },
  },
  {
    category: "groceries",
    subcategory: "staples",
    url: "https://www.bigbasket.com/ps/?q=staples",
    selectors: {
      item: "div.SKUDeck___StyledDiv-sc-1e5d9gk-0",
      name: "h3",
      quantity: "span.hZcweF span",
      actualPrice: "span.a-text-price",
      discountedPrice: "span.knDrlZ",
      discountDetail: null,
      image: "img",
      details: null,
      link: "a",
    },
  },
  {
    category: "groceries",
    subcategory: "snacks",
    url: "https://www.bigbasket.com/ps/?q=snacks",
    selectors: {
      item: "div.SKUDeck___StyledDiv-sc-1e5d9gk-0",
      name: "h3",
      quantity: "span.hZcweF span",
      actualPrice: "span.a-text-price",
      discountedPrice: "span.knDrlZ",
      discountDetail: null,
      image: "img",
      details: null,
      link: "a",
    },
  },
  {
    category: "groceries",
    subcategory: "beverages",
    url: "https://www.bigbasket.com/ps/?q=beverages",
    selectors: {
      item: "div.SKUDeck___StyledDiv-sc-1e5d9gk-0",
      name: "h3",
      quantity: "span.hZcweF span",
      actualPrice: "span.a-text-price",
      discountedPrice: "span.knDrlZ",
      discountDetail: null,
      image: "img",
      details: null,
      link: "a",
    },
  },
  {
    category: "groceries",
    subcategory: "dairy",
    url: "https://www.bigbasket.com/ps/?q=dairy",
    selectors: {
      item: "div.SKUDeck___StyledDiv-sc-1e5d9gk-0",
      name: "h3",
      quantity: "span.hZcweF span",
      actualPrice: "span.a-text-price",
      discountedPrice: "span.knDrlZ",
      discountDetail: null,
      image: "img",
      details: null,
      link: "a",
    },
  },
  {
    category: "groceries",
    subcategory: "bakery",
    url: "https://www.bigbasket.com/ps/?q=bakery",
    selectors: {
      item: "div.SKUDeck___StyledDiv-sc-1e5d9gk-0",
      name: "h3",
      quantity: "span.hZcweF span",
      actualPrice: "span.a-text-price",
      discountedPrice: "span.knDrlZ",
      discountDetail: null,
      image: "img",
      details: null,
      link: "a",
    },
  },

  /* ===================== HOUSEHOLD & CARE ===================== */

  {
    category: "household",
    subcategory: "care",
    url: "https://www.bigbasket.com/ps/?q=household+care",
    selectors: {
      item: "div.SKUDeck___StyledDiv-sc-1e5d9gk-0",
      name: "h3",
      quantity: "span.hZcweF span",
      actualPrice: "span.a-text-price",
      discountedPrice: "span.knDrlZ",
      discountDetail: null,
      image: "img",
      details: null,
      link: "a",
    },
  },

  /* ===================== PERSONAL CARE ===================== */

  {
    category: "personal care",
    subcategory: "skincare",
    url: "https://www.bigbasket.com/ps/?q=skincare",
    selectors: {
      item: "div.SKUDeck___StyledDiv-sc-1e5d9gk-0",
      name: "h3",
      quantity: "span.hZcweF span",
      actualPrice: "span.a-text-price",
      discountedPrice: "span.knDrlZ",
      discountDetail: null,
      image: "img",
      details: null,
      link: "a",
    },
  },
  {
    category: "personal care",
    subcategory: "haircare",
    url: "https://www.bigbasket.com/ps/?q=haircare",
    selectors: {
      item: "div.SKUDeck___StyledDiv-sc-1e5d9gk-0",
      name: "h3",
      quantity: "span.hZcweF span",
      actualPrice: "span.a-text-price",
      discountedPrice: "span.knDrlZ",
      discountDetail: null,
      image: "img",
      details: null,
      link: "a",
    },
  },
  {
    category: "personal care",
    subcategory: "grooming",
    url: "https://www.bigbasket.com/ps/?q=grooming",
    selectors: {
      item: "div.SKUDeck___StyledDiv-sc-1e5d9gk-0",
      name: "h3",
      quantity: "span.hZcweF span",
      actualPrice: "span.a-text-price",
      discountedPrice: "span.knDrlZ",
      discountDetail: null,
      image: "img",
      details: null,
      link: "a",
    },
  },
  {
    category: "personal care",
    subcategory: "wellness",
    url: "https://www.bigbasket.com/ps/?q=wellness",
    selectors: {
      item: "div.SKUDeck___StyledDiv-sc-1e5d9gk-0",
      name: "h3",
      quantity: "span.hZcweF span",
      actualPrice: "span.a-text-price",
      discountedPrice: "span.knDrlZ",
      discountDetail: null,
      image: "img",
      details: null,
      link: "a",
    },
  },
  {
    category: "personal care",
    subcategory: "hygiene",
    url: "https://www.bigbasket.com/ps/?q=hygiene",
    selectors: {
      item: "div.SKUDeck___StyledDiv-sc-1e5d9gk-0",
      name: "h3",
      quantity: "span.hZcweF span",
      actualPrice: "span.a-text-price",
      discountedPrice: "span.knDrlZ",
      discountDetail: null,
      image: "img",
      details: null,
      link: "a",
    },
  },
  {
    category: "personal care",
    subcategory: "supplements",
    url: "https://www.bigbasket.com/ps/?q=supplements",
    selectors: {
      item: "div.SKUDeck___StyledDiv-sc-1e5d9gk-0",
      name: "h3",
      quantity: "span.hZcweF span",
      actualPrice: "span.a-text-price",
      discountedPrice: "span.knDrlZ",
      discountDetail: null,
      image: "img",
      details: null,
      link: "a",
    },
  },
];
