const amazonCategories = [
  {
    category: "electronics",
    subcategory: "mobiles",
    url: "https://www.amazon.in/s?k=mobiles",
    selectors: {
      item: "div.s-result-item",
      name: "h2 a span",
      quantity: null,
      actualPrice: "span.a-text-price span",
      discountedPrice: "span.a-price-whole",
      discountDetail: null,
      image: "img.s-image",
      details: null,
      link: "h2 a",
    },
  },
  {
    category: "electronics",
    subcategory: "laptops",
    url: "https://www.amazon.in/s?k=laptops",
    selectors: {
      item: "div.s-result-item",
      name: "h2 a span",
      quantity: null,
      actualPrice: "span.a-text-price span",
      discountedPrice: "span.a-price-whole",
      discountDetail: null,
      image: "img.s-image",
      details: null,
      link: "h2 a",
    },
  },
  {
    category: "electronics",
    subcategory: "tablets",
    url: "https://www.amazon.in/s?k=tablets",
    selectors: {
      item: "div.s-result-item",
      name: "h2 a span",
      quantity: null,
      actualPrice: "span.a-text-price span",
      discountedPrice: "span.a-price-whole",
      discountDetail: null,
      image: "img.s-image",
      details: null,
      link: "h2 a",
    },
  },
  {
    category: "electronics",
    subcategory: "wearables",
    url: "https://www.amazon.in/s?k=smartwatch",
    selectors: {
      item: "div.s-result-item",
      name: "h2 a span",
      quantity: null,
      actualPrice: "span.a-text-price span",
      discountedPrice: "span.a-price-whole",
      discountDetail: null,
      image: "img.s-image",
      details: null,
      link: "h2 a",
    },
  },
  {
    category: "electronics",
    subcategory: "audio",
    url: "https://www.amazon.in/s?k=headphones",
    selectors: {
      item: "div.s-result-item",
      name: "h2 a span",
      quantity: null,
      actualPrice: "span.a-text-price span",
      discountedPrice: "span.a-price-whole",
      discountDetail: null,
      image: "img.s-image",
      details: null,
      link: "h2 a",
    },
  },
  {
    category: "electronics",
    subcategory: "cameras",
    url: "https://www.amazon.in/s?k=camera",
    selectors: {
      item: "div.s-result-item",
      name: "h2 a span",
      quantity: null,
      actualPrice: "span.a-text-price span",
      discountedPrice: "span.a-price-whole",
      discountDetail: null,
      image: "img.s-image",
      details: null,
      link: "h2 a",
    },
  },
  {
    category: "electronics",
    subcategory: "gaming",
    url: "https://www.amazon.in/s?k=gaming",
    selectors: {
      item: "div.s-result-item",
      name: "h2 a span",
      quantity: null,
      actualPrice: "span.a-text-price span",
      discountedPrice: "span.a-price-whole",
      discountDetail: null,
      image: "img.s-image",
      details: null,
      link: "h2 a",
    },
  },
  {
    category: "electronics",
    subcategory: "accessories",
    url: "https://www.amazon.in/s?k=mobile+accessories",
    selectors: {
      item: "div.s-result-item",
      name: "h2 a span",
      quantity: null,
      actualPrice: "span.a-text-price span",
      discountedPrice: "span.a-price-whole",
      discountDetail: null,
      image: "img.s-image",
      details: null,
      link: "h2 a",
    },
  },

  {
    category: "fashion",
    subcategory: "mens",
    url: "https://www.amazon.in/s?k=mens+clothing",
    selectors: {
      item: "div.s-result-item",
      name: "h2 a span",
      quantity: null,
      actualPrice: "span.a-text-price span",
      discountedPrice: "span.a-price-whole",
      discountDetail: null,
      image: "img.s-image",
      details: null,
      link: "h2 a",
    },
  },
  {
    category: "fashion",
    subcategory: "womens",
    url: "https://www.amazon.in/s?k=womens+clothing",
    selectors: {
      item: "div.s-result-item",
      name: "h2 a span",
      quantity: null,
      actualPrice: "span.a-text-price span",
      discountedPrice: "span.a-price-whole",
      discountDetail: null,
      image: "img.s-image",
      details: null,
      link: "h2 a",
    },
  },
  {
    category: "fashion",
    subcategory: "kids",
    url: "https://www.amazon.in/s?k=kids+clothing",
    selectors: {
      item: "div.s-result-item",
      name: "h2 a span",
      quantity: null,
      actualPrice: "span.a-text-price span",
      discountedPrice: "span.a-price-whole",
      discountDetail: null,
      image: "img.s-image",
      details: null,
      link: "h2 a",
    },
  },
  {
    category: "fashion",
    subcategory: "footwear",
    url: "https://www.amazon.in/s?k=footwear",
    selectors: {
      item: "div.s-result-item",
      name: "h2 a span",
      quantity: null,
      actualPrice: "span.a-text-price span",
      discountedPrice: "span.a-price-whole",
      discountDetail: null,
      image: "img.s-image",
      details: null,
      link: "h2 a",
    },
  },
  {
    category: "fashion",
    subcategory: "bags",
    url: "https://www.amazon.in/s?k=bags",
    selectors: {
      item: "div.s-result-item",
      name: "h2 a span",
      quantity: null,
      actualPrice: "span.a-text-price span",
      discountedPrice: "span.a-price-whole",
      discountDetail: null,
      image: "img.s-image",
      details: null,
      link: "h2 a",
    },
  },
  {
    category: "fashion",
    subcategory: "watches",
    url: "https://www.amazon.in/s?k=watches",
    selectors: {
      item: "div.s-result-item",
      name: "h2 a span",
      quantity: null,
      actualPrice: "span.a-text-price span",
      discountedPrice: "span.a-price-whole",
      discountDetail: null,
      image: "img.s-image",
      details: null,
      link: "h2 a",
    },
  },
  {
    category: "fashion",
    subcategory: "jewelry",
    url: "https://www.amazon.in/s?k=jewelry",
    selectors: {
      item: "div.s-result-item",
      name: "h2 a span",
      quantity: null,
      actualPrice: "span.a-text-price span",
      discountedPrice: "span.a-price-whole",
      discountDetail: null,
      image: "img.s-image",
      details: null,
      link: "h2 a",
    },
  },
  {
    category: "fashion",
    subcategory: "ethnic",
    url: "https://www.amazon.in/s?k=ethnic+wear",
    selectors: {
      item: "div.s-result-item",
      name: "h2 a span",
      quantity: null,
      actualPrice: "span.a-text-price span",
      discountedPrice: "span.a-price-whole",
      discountDetail: null,
      image: "img.s-image",
      details: null,
      link: "h2 a",
    },
  },

  {
    category: "home",
    subcategory: "furniture",
    url: "https://www.amazon.in/s?k=furniture",
    selectors: {
      item: "div.s-result-item",
      name: "h2 a span",
      quantity: null,
      actualPrice: "span.a-text-price span",
      discountedPrice: "span.a-price-whole",
      discountDetail: null,
      image: "img.s-image",
      details: null,
      link: "h2 a",
    },
  },
  {
    category: "home",
    subcategory: "kitchen",
    url: "https://www.amazon.in/s?k=kitchen+items",
    selectors: {
      item: "div.s-result-item",
      name: "h2 a span",
      quantity: null,
      actualPrice: "span.a-text-price span",
      discountedPrice: "span.a-price-whole",
      discountDetail: null,
      image: "img.s-image",
      details: null,
      link: "h2 a",
    },
  },
  {
    category: "home",
    subcategory: "decor",
    url: "https://www.amazon.in/s?k=home+decor",
    selectors: {
      item: "div.s-result-item",
      name: "h2 a span",
      quantity: null,
      actualPrice: "span.a-text-price span",
      discountedPrice: "span.a-price-whole",
      discountDetail: null,
      image: "img.s-image",
      details: null,
      link: "h2 a",
    },
  },
  {
    category: "home",
    subcategory: "storage",
    url: "https://www.amazon.in/s?k=storage+organizer",
    selectors: {
      item: "div.s-result-item",
      name: "h2 a span",
      quantity: null,
      actualPrice: "span.a-text-price span",
      discountedPrice: "span.a-price-whole",
      discountDetail: null,
      image: "img.s-image",
      details: null,
      link: "h2 a",
    },
  },
  {
    category: "home",
    subcategory: "appliances",
    url: "https://www.amazon.in/s?k=home+appliances",
    selectors: {
      item: "div.s-result-item",
      name: "h2 a span",
      quantity: null,
      actualPrice: "span.a-text-price span",
      discountedPrice: "span.a-price-whole",
      discountDetail: null,
      image: "img.s-image",
      details: null,
      link: "h2 a",
    },
  },
  {
    category: "home",
    subcategory: "lighting",
    url: "https://www.amazon.in/s?k=lighting",
    selectors: {
      item: "div.s-result-item",
      name: "h2 a span",
      quantity: null,
      actualPrice: "span.a-text-price span",
      discountedPrice: "span.a-price-whole",
      discountDetail: null,
      image: "img.s-image",
      details: null,
      link: "h2 a",
    },
  },
  {
    category: "home",
    subcategory: "bedding",
    url: "https://www.amazon.in/s?k=bedding",
    selectors: {
      item: "div.s-result-item",
      name: "h2 a span",
      quantity: null,
      actualPrice: "span.a-text-price span",
      discountedPrice: "span.a-price-whole",
      discountDetail: null,
      image: "img.s-image",
      details: null,
      link: "h2 a",
    },
  },
  {
    category: "home",
    subcategory: "cleaning",
    url: "https://www.amazon.in/s?k=cleaning+supplies",
    selectors: {
      item: "div.s-result-item",
      name: "h2 a span",
      quantity: null,
      actualPrice: "span.a-text-price span",
      discountedPrice: "span.a-price-whole",
      discountDetail: null,
      image: "img.s-image",
      details: null,
      link: "h2 a",
    },
  },

  {
    category: "care",
    subcategory: "skincare",
    url: "https://www.amazon.in/s?k=skincare",
    selectors: {
      item: "div.s-result-item",
      name: "h2 a span",
      quantity: null,
      actualPrice: "span.a-text-price span",
      discountedPrice: "span.a-price-whole",
      discountDetail: null,
      image: "img.s-image",
      details: null,
      link: "h2 a",
    },
  },
  {
    category: "care",
    subcategory: "haircare",
    url: "https://www.amazon.in/s?k=haircare",
    selectors: {
      item: "div.s-result-item",
      name: "h2 a span",
      quantity: null,
      actualPrice: "span.a-text-price span",
      discountedPrice: "span.a-price-whole",
      discountDetail: null,
      image: "img.s-image",
      details: null,
      link: "h2 a",
    },
  },
  {
    category: "care",
    subcategory: "makeup",
    url: "https://www.amazon.in/s?k=makeup",
    selectors: {
      item: "div.s-result-item",
      name: "h2 a span",
      quantity: null,
      actualPrice: "span.a-text-price span",
      discountedPrice: "span.a-price-whole",
      discountDetail: null,
      image: "img.s-image",
      details: null,
      link: "h2 a",
    },
  },
  {
    category: "care",
    subcategory: "grooming",
    url: "https://www.amazon.in/s?k=grooming",
    selectors: {
      item: "div.s-result-item",
      name: "h2 a span",
      quantity: null,
      actualPrice: "span.a-text-price span",
      discountedPrice: "span.a-price-whole",
      discountDetail: null,
      image: "img.s-image",
      details: null,
      link: "h2 a",
    },
  },
  {
    category: "care",
    subcategory: "fragrance",
    url: "https://www.amazon.in/s?k=fragrance",
    selectors: {
      item: "div.s-result-item",
      name: "h2 a span",
      quantity: null,
      actualPrice: "span.a-text-price span",
      discountedPrice: "span.a-price-whole",
      discountDetail: null,
      image: "img.s-image",
      details: null,
      link: "h2 a",
    },
  },
  {
    category: "care",
    subcategory: "wellness",
    url: "https://www.amazon.in/s?k=wellness",
    selectors: {
      item: "div.s-result-item",
      name: "h2 a span",
      quantity: null,
      actualPrice: "span.a-text-price span",
      discountedPrice: "span.a-price-whole",
      discountDetail: null,
      image: "img.s-image",
      details: null,
      link: "h2 a",
    },
  },
  {
    category: "care",
    subcategory: "hygiene",
    url: "https://www.amazon.in/s?k=hygiene",
    selectors: {
      item: "div.s-result-item",
      name: "h2 a span",
      quantity: null,
      actualPrice: "span.a-text-price span",
      discountedPrice: "span.a-price-whole",
      discountDetail: null,
      image: "img.s-image",
      details: null,
      link: "h2 a",
    },
  },
  {
    category: "care",
    subcategory: "supplements",
    url: "https://www.amazon.in/s?k=supplements",
    selectors: {
      item: "div.s-result-item",
      name: "h2 a span",
      quantity: null,
      actualPrice: "span.a-text-price span",
      discountedPrice: "span.a-price-whole",
      discountDetail: null,
      image: "img.s-image",
      details: null,
      link: "h2 a",
    },
  },

  {
    category: "groceries",
    subcategory: "fruits",
    url: "https://www.amazon.in/s?k=fruits",
    selectors: {
      item: "div.s-result-item",
      name: "h2 a span",
      quantity: null,
      actualPrice: "span.a-text-price span",
      discountedPrice: "span.a-price-whole",
      discountDetail: null,
      image: "img.s-image",
      details: null,
      link: "h2 a",
    },
  },
  {
    category: "groceries",
    subcategory: "vegetables",
    url: "https://www.amazon.in/s?k=vegetables",
    selectors: {
      item: "div.s-result-item",
      name: "h2 a span",
      quantity: null,
      actualPrice: "span.a-text-price span",
      discountedPrice: "span.a-price-whole",
      discountDetail: null,
      image: "img.s-image",
      details: null,
      link: "h2 a",
    },
  },
  {
    category: "groceries",
    subcategory: "staples",
    url: "https://www.amazon.in/s?k=staples",
    selectors: {
      item: "div.s-result-item",
      name: "h2 a span",
      quantity: null,
      actualPrice: "span.a-text-price span",
      discountedPrice: "span.a-price-whole",
      discountDetail: null,
      image: "img.s-image",
      details: null,
      link: "h2 a",
    },
  },
  {
    category: "groceries",
    subcategory: "snacks",
    url: "https://www.amazon.in/s?k=snacks",
    selectors: {
      item: "div.s-result-item",
      name: "h2 a span",
      quantity: null,
      actualPrice: "span.a-text-price span",
      discountedPrice: "span.a-price-whole",
      discountDetail: null,
      image: "img.s-image",
      details: null,
      link: "h2 a",
    },
  },
  {
    category: "groceries",
    subcategory: "beverages",
    url: "https://www.amazon.in/s?k=beverages",
    selectors: {
      item: "div.s-result-item",
      name: "h2 a span",
      quantity: null,
      actualPrice: "span.a-text-price span",
      discountedPrice: "span.a-price-whole",
      discountDetail: null,
      image: "img.s-image",
      details: null,
      link: "h2 a",
    },
  },
  {
    category: "groceries",
    subcategory: "dairy",
    url: "https://www.amazon.in/s?k=dairy",
    selectors: {
      item: "div.s-result-item",
      name: "h2 a span",
      quantity: null,
      actualPrice: "span.a-text-price span",
      discountedPrice: "span.a-price-whole",
      discountDetail: null,
      image: "img.s-image",
      details: null,
      link: "h2 a",
    },
  },
  {
    category: "groceries",
    subcategory: "bakery",
    url: "https://www.amazon.in/s?k=bakery",
    selectors: {
      item: "div.s-result-item",
      name: "h2 a span",
      quantity: null,
      actualPrice: "span.a-text-price span",
      discountedPrice: "span.a-price-whole",
      discountDetail: null,
      image: "img.s-image",
      details: null,
      link: "h2 a",
    },
  },
  {
    category: "groceries",
    subcategory: "household",
    url: "https://www.amazon.in/s?k=household+essentials",
    selectors: {
      item: "div.s-result-item",
      name: "h2 a span",
      quantity: null,
      actualPrice: "span.a-text-price span",
      discountedPrice: "span.a-price-whole",
      discountDetail: null,
      image: "img.s-image",
      details: null,
      link: "h2 a",
    },
  },
];
