const flipkartCategories = [
  /* ===================== FASHION ===================== */
  
  {
    category: "fashion",
    subcategory: "womens",
    url: "https://www.flipkart.com/search?q=womens+clothing",
    selectors: {
      item: "div._1AtVbE",
      name: "a.IRpwTa",
      quantity: "div._3LWZlK",
      actualPrice: "div._30jeq3",
      discountedPrice: "div._3I9_wc",
      discountDetail: "div._3Ay6Sb span",
      image: "img",
      details: "div.o_eY3O li",
      link: "a.atJtCj",
    },
  },
  {
    category: "fashion",
    subcategory: "kids",
    url: "https://www.flipkart.com/search?q=kids+clothing",
    selectors: {
      item: "div._1AtVbE",
      name: "a.IRpwTa",
      quantity: "div._3LWZlK",
      actualPrice: "div._30jeq3",
      discountedPrice: "div._3I9_wc",
      discountDetail: "div._3Ay6Sb span",
      image: "img",
      details: "div.o_eY3O li",
      link: "a.atJtCj",
    },
  },
  {
    category: "fashion",
    subcategory: "footwear",
    url: "https://www.flipkart.com/search?q=footwear",
    selectors: {
      item: "div._1AtVbE",
      name: "a.IRpwTa",
      quantity: "div._3LWZlK",
      actualPrice: "div._30jeq3",
      discountedPrice: "div._3I9_wc",
      discountDetail: "div._3Ay6Sb span",
      image: "img",
      details: "div.o_eY3O li",
      link: "a.atJtCj",
    },
  },
  {
    category: "fashion",
    subcategory: "bags",
    url: "https://www.flipkart.com/search?q=bags",
    selectors: {
      item: "div._1AtVbE",
      name: "a.IRpwTa",
      quantity: "div._3LWZlK",
      actualPrice: "div._30jeq3",
      discountedPrice: "div._3I9_wc",
      discountDetail: "div._3Ay6Sb span",
      image: "img",
      details: "div.o_eY3O li",
      link: "a.atJtCj",
    },
  },
  {
    category: "fashion",
    subcategory: "watches",
    url: "https://www.flipkart.com/search?q=watches",
    selectors: {
      item: "div._1AtVbE",
      name: "a.IRpwTa",
      quantity: "div._3LWZlK",
      actualPrice: "div._30jeq3",
      discountedPrice: "div._3I9_wc",
      discountDetail: "div._3Ay6Sb span",
      image: "img",
      details: "div.o_eY3O li",
      link: "a.atJtCj",
    },
  },
  {
    category: "fashion",
    subcategory: "jewelry",
    url: "https://www.flipkart.com/search?q=jewelry",
    selectors: {
      item: "div._1AtVbE",
      name: "a.IRpwTa",
      quantity: "div._3LWZlK",
      actualPrice: "div._30jeq3",
      discountedPrice: "div._3I9_wc",
      discountDetail: "div._3Ay6Sb span",
      image: "img",
      details: "div.o_eY3O li",
      link: "a.atJtCj",
    },
  },
  {
    category: "fashion",
    subcategory: "ethnic",
    url: "https://www.flipkart.com/search?q=ethnic+wear",
    selectors: {
      item: "div._1AtVbE",
      name: "a.IRpwTa",
      quantity: "div._3LWZlK",
      actualPrice: "div._30jeq3",
      discountedPrice: "div._3I9_wc",
      discountDetail: "div._3Ay6Sb span",
      image: "img",
      details: "div.o_eY3O li",
      link: "a.atJtCj",
    },
  },

  /* ===================== HOME ===================== */

  {
    category: "home",
    subcategory: "kitchen",
    url: "https://www.flipkart.com/search?q=kitchen",
    selectors: {
      item: "div._1AtVbE",
      name: "div._4rR01T",
      quantity: "div._3LWZlK",
      actualPrice: "div._30jeq3",
      discountedPrice: "div._3I9_wc",
      discountDetail: "div._3Ay6Sb span",
      image: "img",
      details: "div.o_eY3O li",
      link: "a.atJtCj",
    },
  },
  {
    category: "home",
    subcategory: "decor",
    url: "https://www.flipkart.com/search?q=home+decor",
    selectors: {
      item: "div._1AtVbE",
      name: "div._4rR01T",
      quantity: "div._3LWZlK",
      actualPrice: "div._30jeq3",
      discountedPrice: "div._3I9_wc",
      discountDetail: "div._3Ay6Sb span",
      image: "img",
      details: "div.o_eY3O li",
      link: "a.atJtCj",
    },
  },
  {
    category: "home",
    subcategory: "storage",
    url: "https://www.flipkart.com/search?q=storage",
    selectors: {
      item: "div._1AtVbE",
      name: "div._4rR01T",
      quantity: "div._3LWZlK",
      actualPrice: "div._30jeq3",
      discountedPrice: "div._3I9_wc",
      discountDetail: "div._3Ay6Sb span",
      image: "img",
      details: "div.o_eY3O li",
      link: "a.atJtCj",
    },
  },
  {
    category: "home",
    subcategory: "appliances",
    url: "https://www.flipkart.com/search?q=home+appliances",
    selectors: {
      item: "div._1AtVbE",
      name: "div._4rR01T",
      quantity: "div._3LWZlK",
      actualPrice: "div._30jeq3",
      discountedPrice: "div._3I9_wc",
      discountDetail: "div._3Ay6Sb span",
      image: "img",
      details: "div.o_eY3O li",
      link: "a.atJtCj",
    },
  },
  {
    category: "home",
    subcategory: "lighting",
    url: "https://www.flipkart.com/search?q=lighting",
    selectors: {
      item: "div._1AtVbE",
      name: "div._4rR01T",
      quantity: "div._3LWZlK",
      actualPrice: "div._30jeq3",
      discountedPrice: "div._3I9_wc",
      discountDetail: "div._3Ay6Sb span",
      image: "img",
      details: "div.o_eY3O li",
      link: "a.atJtCj",
    },
  },
  {
    category: "home",
    subcategory: "bedding",
    url: "https://www.flipkart.com/search?q=bedding",
    selectors: {
      item: "div._1AtVbE",
      name: "div._4rR01T",
      quantity: "div._3LWZlK",
      actualPrice: "div._30jeq3",
      discountedPrice: "div._3I9_wc",
      discountDetail: "div._3Ay6Sb span",
      image: "img",
      details: "div.o_eY3O li",
      link: "a.atJtCj",
    },
  },
  {
    category: "home",
    subcategory: "cleaning",
    url: "https://www.flipkart.com/search?q=cleaning",
    selectors: {
      item: "div._1AtVbE",
      name: "div._4rR01T",
      quantity: "div._3LWZlK",
      actualPrice: "div._30jeq3",
      discountedPrice: "div._3I9_wc",
      discountDetail: "div._3Ay6Sb span",
      image: "img",
      details: "div.o_eY3O li",
      link: "a.atJtCj",
    },
  },

  /* ===================== CARE ===================== */

  {
    category: "care",
    subcategory: "haircare",
    url: "https://www.flipkart.com/search?q=haircare",
    selectors: {
      item: "div._1AtVbE",
      name: "a.IRpwTa",
      quantity: "div._3LWZlK",
      actualPrice: "div._30jeq3",
      discountedPrice: "div._3I9_wc",
      discountDetail: "div._3Ay6Sb span",
      image: "img",
      details: "div.o_eY3O li",
      link: "a.atJtCj",
    },
  },
  {
    category: "care",
    subcategory: "makeup",
    url: "https://www.flipkart.com/search?q=makeup",
    selectors: {
      item: "div._1AtVbE",
      name: "a.IRpwTa",
      quantity: "div._3LWZlK",
      actualPrice: "div._30jeq3",
      discountedPrice: "div._3I9_wc",
      discountDetail: "div._3Ay6Sb span",
      image: "img",
      details: "div.o_eY3O li",
      link: "a.atJtCj",
    },
  },
  {
    category: "care",
    subcategory: "grooming",
    url: "https://www.flipkart.com/search?q=grooming",
    selectors: {
      item: "div._1AtVbE",
      name: "a.IRpwTa",
      quantity: "div._3LWZlK",
      actualPrice: "div._30jeq3",
      discountedPrice: "div._3I9_wc",
      discountDetail: "div._3Ay6Sb span",
      image: "img",
      details: "div.o_eY3O li",
      link: "a.atJtCj",
    },
  },
  {
    category: "care",
    subcategory: "fragrance",
    url: "https://www.flipkart.com/search?q=fragrance",
    selectors: {
      item: "div._1AtVbE",
      name: "a.IRpwTa",
      quantity: "div._3LWZlK",
      actualPrice: "div._30jeq3",
      discountedPrice: "div._3I9_wc",
      discountDetail: "div._3Ay6Sb span",
      image: "img",
      details: "div.o_eY3O li",
      link: "a.atJtCj",
    },
  },
  {
    category: "care",
    subcategory: "wellness",
    url: "https://www.flipkart.com/search?q=wellness",
    selectors: {
      item: "div._1AtVbE",
      name: "a.IRpwTa",
      quantity: "div._3LWZlK",
      actualPrice: "div._30jeq3",
      discountedPrice: "div._3I9_wc",
      discountDetail: "div._3Ay6Sb span",
      image: "img",
      details: "div.o_eY3O li",
      link: "a.atJtCj",
    },
  },
  {
    category: "care",
    subcategory: "hygiene",
    url: "https://www.flipkart.com/search?q=hygiene",
    selectors: {
      item: "div._1AtVbE",
      name: "a.IRpwTa",
      quantity: "div._3LWZlK",
      actualPrice: "div._30jeq3",
      discountedPrice: "div._3I9_wc",
      discountDetail: "div._3Ay6Sb span",
      image: "img",
      details: "div.o_eY3O li",
      link: "a.atJtCj",
    },
  },
  {
    category: "care",
    subcategory: "supplements",
    url: "https://www.flipkart.com/search?q=supplements",
    selectors: {
      item: "div._1AtVbE",
      name: "a.IRpwTa",
      quantity: "div._3LWZlK",
      actualPrice: "div._30jeq3",
      discountedPrice: "div._3I9_wc",
      discountDetail: "div._3Ay6Sb span",
      image: "img",
      details: "div.o_eY3O li",
      link: "a.atJtCj",
    },
  },
];

export default flipkartCategories;
